### PR TITLE
fix: listrr response being treated as a dict

### LINKED ISSUE #959: docker dev listrr - types.SimpleNamespace' object has no attribute 'get'
Hi,

So far, riven is working well with overseer and would like to add listrr to work, however it does not work with 0.20.1 so try with latest dev and it can communicate with listrr however could not execute any list.

Env: 
- Docker image: `docker.io/spoked/riven:dev`
- Config:

```
        "listrr": {
            "update_interval": 300,
            "enabled": true,
            "movie_lists": [],
            "show_lists": [
                "676b8999ad3213fedcf71084"
            ],
            "api_key": "xxxxx"
        },
```

LOG:
```log
24-12-28 09:16:32 | ✔️  SUCCESS   | listrr.__init__ - Listrr initialized!
24-12-28 09:16:40 | 🐞 DEBUG     | program._schedule_services - Scheduled Listrr to run every 300 seconds.
24-12-28 09:16:40 | 🐞 DEBUG     | event_manager.submit_job - Submitting service Listrr to be executed
24-12-28 09:16:40 | 🐞 DEBUG     | event_manager._find_or_create_executor - Created executor for Listrr with 1 max workers.
24-12-28 09:16:40 | ❌ ERROR     | listrr_api.get_items_from_Listrr - An error occurred: 'types.SimpleNamespace' object has no attribute 'get'
```

### PR DESCRIPTION
**Pull request by davidemarcoli**
# Pull Request Check List

Resolves: #975, Resolves #959

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

## Summary by CodeRabbit

- **Refactor**
	- Improved the method for retrieving IMDb IDs in the Listrr API, enhancing attribute access and error handling.
	- Enhanced duplicate handling with warning logs for skipped duplicates.

### CODE REVIEW

File: src/program/apis/listrr_api.py [hunk 1]
```diff
@@ -55,13 +55,13 @@ def get_items_from_Listrr(self, content_type, content_lists) -> list[MediaItem]
...
-                        imdb_id = item.get("imDbId")
+                    total_pages = getattr(data, "pages", 1)
+                    for item in getattr(data, "items", []):
+                        imdb_id = getattr(item,"imDbId")
                         if imdb_id:
                             unique_ids.add(imdb_id)
-                        elif content_type == "Movies" and item.get("tmDbId"):
-                            imdb_id = self.trakt_api.get_imdbid_from_tmdb(item["tmDbId"])
+                        elif content_type == "Movies" and getattr(item, "tmDbId"):
+                            imdb_id = self.trakt_api.get_imdbid_from_tmdb(getattr(item, "tmDbId"))
```
[the remark this answers is not in the document]
Comment (dreulavelle) [reply src/program/apis/listrr_api.py:64]: @davidemarcoli its got a point :D

**Review by dreulavelle — CHANGES_REQUESTED** [review]
take note of the code rabbit suggestion

File: src/program/apis/listrr_api.py [hunk 2]
```diff
@@ -55,15 +55,26 @@ def get_items_from_Listrr(self, content_type, content_lists) -> list[MediaItem]
...
+                            imdb_id = item.imDbId or (
+                                self.trakt_api.get_imdbid_from_tmdb(item.tmDbId) 
+                                if content_type == "Movies" and item.tmDbId 
+                                else None
+                            )
+
+                            if not imdb_id:
+                                continue
+                            if imdb_id in unique_ids:
+                                logger.warning(f"Skipping duplicate item {imdb_id}")
```
Comment (dreulavelle) [inline src/program/apis/listrr_api.py:71]: we can remove this log message as its going to hit this quite a lot anyways by default?

**Review by dreulavelle — APPROVED** [review]
