### ISSUE TITLE
docker dev listrr - types.SimpleNamespace' object has no attribute 'get'

### ISSUE THREAD

**Issue by bacnh85** [rivenmedia/riven#959]
Hi,

So far, riven is working well with overseer and would like to add listrr to work, however it does not work with 0.20.1 so try with latest dev and it can communicate with listrr however could not execute any list.

Env: 
- Docker image: `docker.io/spoked/riven:dev`
- Config:

```
        "listrr": {
            "update_interval": 300,
            "enabled": true,
            "movie_lists": [],
            "show_lists": [
                "676b8999ad3213fedcf71084"
            ],
            "api_key": "xxxxx"
        },
```

LOG:
```log
24-12-28 09:16:32 | ✔️  SUCCESS   | listrr.__init__ - Listrr initialized!
24-12-28 09:16:40 | 🐞 DEBUG     | program._schedule_services - Scheduled Listrr to run every 300 seconds.
24-12-28 09:16:40 | 🐞 DEBUG     | event_manager.submit_job - Submitting service Listrr to be executed
24-12-28 09:16:40 | 🐞 DEBUG     | event_manager._find_or_create_executor - Created executor for Listrr with 1 max workers.
24-12-28 09:16:40 | ❌ ERROR     | listrr_api.get_items_from_Listrr - An error occurred: 'types.SimpleNamespace' object has no attribute 'get'
```

**Comment by bacnh85** [comment]
@dreulavelle  I tried to make development env however backend/main.py is not available, so I think README may need to be updated as well.
```bash
poetry run python backend/main.py
```

**Comment by machetie** [comment]
Consolidating Docker-related issues:

Related issue:
- #925 - Custom port specification in Docker

Will track all Docker configuration and service issues here for better coordination.

**Comment by wolfemir** [comment]
NOTE: listrr is not working
